export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        brand: {
          50:  "#fef2f2",
          100: "#fee2e2",
          200: "#fecaca",
          300: "#fca5a5",
          400: "#f87171",
          500: "#ef4444",
          600: "#dc2626",
          700: "#b91c1c",
          800: "#991b1b",
          900: "#7f1d1d",
        },
        surface: {
          DEFAULT: "var(--surface)",
          2: "var(--surface-2)",
          3: "var(--surface-3)",
          4: "var(--surface-4)",
          bg: "var(--surface-bg)",
          card: "var(--surface-card)",
        },
        border: {
          DEFAULT: "var(--border)",
          light: "var(--border-light)",
          brand: "var(--border-brand)",
          subtle: "var(--border-subtle)",
        },
        text: {
          primary: "var(--text-primary)",
          secondary: "var(--text-secondary)",
          muted: "var(--text-muted)",
          subtle: "var(--text-subtle)",
          invert: "var(--text-invert)",
        },
        shadow: {
          xs: "var(--shadow-xs)",
          sm: "var(--shadow-sm)",
          md: "var(--shadow-md)",
          lg: "var(--shadow-lg)",
          xl: "var(--shadow-xl)",
        },
      },
      fontFamily: {
        sans:    ["Inter", "system-ui", "sans-serif"],
        display: ["Space Grotesk", "system-ui", "sans-serif"],
        mono:    ["JetBrains Mono", "monospace"],
      },
      borderRadius: {
        "2xl": "1rem",
        "3xl": "1.25rem",
        "4xl": "1.5rem",
        "5xl": "1.75rem",
        "6xl": "2rem",
      },
      boxShadow: {
        xs: "var(--shadow-xs)",
        sm: "var(--shadow-sm)",
        md: "var(--shadow-md)",
        lg: "var(--shadow-lg)",
        xl: "var(--shadow-xl)",
        card:       "var(--shadow-card)",
        "card-hover": "var(--shadow-card-hover)",
        nav:        "var(--shadow-nav)",
        modal:      "var(--shadow-modal)",
        float:      "var(--shadow-float)",
      },
      spacing: {
        "1.5": "6px",
        "2.5": "10px",
        "3.5": "14px",
        "4.5": "18px",
        "5.5": "22px",
        "6.5": "28px",
        "7.5": "36px",
        "8.5": "44px",
        "9.5": "56px",
        "10.5": "72px",
      },
      animation: {
        "fade-up":    "fadeUp 0.35s cubic-bezier(0.22, 0.61, 0.36, 1) both",
        "fade-in":    "fadeIn 0.24s ease both",
        "pulse-ring": "pulseRing 2s ease-in-out infinite",
        "spin-slow":  "spin 1.2s linear infinite",
        "slide-in":   "slideIn 0.3s cubic-bezier(0.22, 0.61, 0.36, 1) both",
        "bounce-in":  "bounceIn 0.4s cubic-bezier(0.22, 0.61, 0.36, 1) both",
        "glow":       "glow 2s ease-in-out infinite alternate",
      },
      keyframes: {
        fadeUp: {
          from: { opacity: "0", transform: "translateY(12px)" },
          to:   { opacity: "1", transform: "translateY(0)" },
        },
        fadeIn: {
          from: { opacity: "0" },
          to:   { opacity: "1" },
        },
        pulseRing: {
          "0%, 100%": { transform: "scale(1)", opacity: "1" },
          "50%":      { transform: "scale(1.06)", opacity: "0.65" },
        },
        slideIn: {
          from: { opacity: "0", transform: "translateX(-16px)" },
          to:   { opacity: "1", transform: "translateX(0)" },
        },
        bounceIn: {
          "0%":   { opacity: "0", transform: "scale(0.8)" },
          "50%":  { opacity: "1", transform: "scale(1.05)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
        glow: {
          from: { boxShadow: "0 0 5px rgba(220,38,38,0.3)" },
          to:   { boxShadow: "0 0 15px rgba(220,38,38,0.6)" },
        },
      },
      transitionTimingFunction: {
        "spring": "cubic-bezier(0.16, 1, 0.3, 1)",
        "out": "cubic-bezier(0.22, 0.61, 0.36, 1)",
        "in-out": "cubic-bezier(0.4, 0, 0.2, 1)",
      },
      transitionDuration: {
        "fast": "0.15s",
        "base": "0.2s",
        "slow": "0.3s",
        "spring": "0.35s",
      },
      backdropBlur: {
        xs: "2px",
        sm: "4px",
        md: "8px",
        lg: "12px",
        xl: "16px",
      },
      backdropOpacity: {
        15: "0.15",
        25: "0.25",
        50: "0.5",
        75: "0.75",
        85: "0.85",
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/typography'),
  ],
};
